# GitHub Sponsors configuration
# Uncomment and set your GitHub username after enabling GitHub Sponsors

github: retailbox-automation

# Optional: Add other funding platforms
# patreon: your_username
# ko_fi: your_username
# buy_me_a_coffee: your_username
